### PR TITLE
Implemented more SFTP methods

### PR DESCRIPTION
**Pull request by brabanod**
In SFTP file: Created a wrapper for the following SFTP methods, implemented in libssh2:
- `libssh2_sftp_mkdir_ex`: create directory
- `libssh2_sftp_rmdir_ex`: remove directory
- `libssh2_sftp_unlink_ex`: remove file
- `libssh2_sftp_rename_ex`: rename file

### CODE REVIEW

**Comment by kyleishie** [comment]
I'm glad I checked for this before beginning the implementation myself.  Can we get this approved soon?

**Comment by jakeheis** [comment]
Looks good, thanks for the contribution!

**Comment by jakeheis** [comment]
Tagged as `0.5.2`

**Comment by brabanod** [comment]
Turns out I forgot to label the functions with `public` so they are not accessible ... I can fix that and create a new pull request or you can fix it if you want? It may be faster that way.

**Comment by brabanod** [comment]
I've opened a the new PR #39 which has this issue fixed. I've also added tests for the new methods.

**Pull request merged**
