### PR TITLE
Fix Glibc errors

### LINKED ISSUE #21: Compiling on Linux
This does not work on Linux currently, unfortunately. I tried the following:

`apt-get install -yq libssh2-1-dev`

However, compiling then results in the following build log:

```
/root/project/.build/checkouts/Shout--6099989465269811733/Sources/Bindings/SFTP.swift:38:32: error: ambiguous use of 'S_IRUSR'
            if (value & CShort(S_IRUSR) == CShort(S_IRUSR)) { permissions.owner.insert(.read) }
                               ^
Glibc.S_IRUSR:1:12: note: found this candidate
public var S_IRUSR: mode_t { get }
           ^
SwiftGlibc.S_IRUSR:1:12: note: found this candidate
public var S_IRUSR: Int32 { get }
           ^
/root/project/.build/checkouts/Shout--6099989465269811733/Sources/Bindings/SFTP.swift:39:32: error: ambiguous use of 'S_IWUSR'
            if (value & CShort(S_IWUSR) == CShort(S_IWUSR)) { permissions.owner.insert(.write) }
                               ^
Glibc.S_IWUSR:1:12: note: found this candidate
public var S_IWUSR: mode_t { get }
           ^
SwiftGlibc.S_IWUSR:1:12: note: found this candidate
public var S_IWUSR: Int32 { get }
           ^
/root/project/.build/checkouts/Shout--6099989465269811733/Sources/Bindings/SFTP.swift:40:32: error: ambiguous use of 'S_IXUSR'
            if (value & CShort(S_IXUSR) == CShort(S_IXUSR)) { permissions.owner.insert(.execute) }
                               ^
Glibc.S_IXUSR:1:12: note: found this candidate
public var S_IXUSR: mode_t { get }
           ^
SwiftGlibc.S_IXUSR:1:12: note: found this candidate
public var S_IXUSR: Int32 { get }
```

Can anyone point me in the right direction for this? Not sure where to start when it comes to getting this up and running on Linux.

### PR DESCRIPTION
**Pull request by jdmcd**
Fixes #21. Thanks for the help, @vzsg!

### CODE REVIEW

**Comment by vzsg** [comment]
Erm. Hi. I didn't expect my fork to show up like this.

Some explanation about the changes:

- Swift 4.2 allows us to declare system libraries inside the project, without needing a separate dependency repo. That's what the first commit is about, dropping CSSH.  
But it's a breaking change for the package.
- The second commit is the more important thing for the issue @mcdappdev is experiencing: installing Shout along with SwiftNIO causes a symbol clash, and prefixing the constants with `Foundation.` fixes that. You might want to cherry pick that in nevertheless.

**Comment by jakeheis** [comment]
I think I'd like to get one more version of `Shout` out that supports Swift 4.0, so if this PR could be split into two -- one that fixes the symbol crash, and one that updates `Package.swift` to use the new system libraries feature -- that would be ideal

**Comment by jdmcd** [comment]
Agreed, that sounds like a good plan. I don't have much bandwidth the next week or so as I'll be mostly offline but I can loop back on this after. Thanks, Jake!

**Comment by vzsg** [comment]
Check out #22. The other part is completely optional, and you can salvage the target setup from gotranseo's or my fork later if you want.

**Comment by jdmcd** [comment]
Perfect, I’ll close this for now then. Thanks @vzsg!

**Pull request closed without merging**
